# Maintainer: Arthur de Oliveira Pereira <arthcomicando@gmail.com>
pkgname=my-package-dependecies-for-i3
pkgver=20190330
pkgrel=1
pkgdesc='All packages needed to run my minimal Arch Linux.'
arch=('any')
license=('custom:Public Domain')
checkdepends=()
install=()
depends=('adobe-source-code-pro-fonts'
	 'adobe-source-sans-pro-fonts'
	 'adobe-source-serif-pro-fonts'
	 'awesome-terminal-fonts'
	 'android-tools'
	 'font-mathematica'
	 'gvfs'
	 'gvfs-afc'
	 'gvfs-smb'
	 'gvfs-gphoto2'
	 'gvfs-mtp'
	 'gvfs-nfs'
	 'noto-fonts'
 	 'noto-fonts-emoji'
	 'noto-fonts-extra'
	 'opendesktop-fonts'
	 'powerline-fonts'
	 'ranger'			# R
	 'atools'			# A
	 'elinks'			# N
	 'ffmpegthumbnailer'		# G
	 'highlight'			# E
	 'mediainfo'			# R
	 'odt2txt'			# .
	 'perl-image-exiftools'		# D
	 'poppler'			# E
	 'python-chardet'		# P
	 'w3m'
	 'terminus-font'
	 'ttf-anonymous-pro'
	 'ttf-dejavu'
	 'ttf-roboto'
	 'ttf-hack'
	 'i3-gaps'
	 'i3lock'
	 'i3status'
	 'scrot'
	 'maim'
	 'bluez'
	 'alsa-firmware'
	 'alsa-tools'
	 'alsa-utils'
	 'pcmanfm'
	 'pulseaudio-alsa'
	 'pulseaudio-bluetooth'
	 'pulseeffects'
	 'pro-audio'
	 'calf'
	 'lsp-plugins'
	 'mda.lv2'
	 'rubberband'
	 'zam-plugins'
	 'lmms'
	 'libsamplerate'
	 'libsndfile'
	 'zita-convolver'
	 'libebur128'
	 'blueberry'
	 'network-manager-applet'
	 'baobab'
	 'conky'
	 'clamscan'
         'ntp'
	 'acpi'
	 'rxvt-unicode'
	 'urxvt-perls'
	 'dosfstools'
	 'ntfs-3g'
	 'exfat-utils'
	 'parted'
	 'gparted'
	 'leafpad'
	 'python3'
	 'chntpw'
	 'arch-install-scripts'
 	 'archiso'
	 'bash-completion'
 	 'ffmpeg'
	 'flashplugin'
	 'hddtemp'
	 'imagemagick'
	 'jre-openjdk'
	 'memtest86+'
	 'rofi'
	 'sbxkb'
	 'speedtest-cli'
	 'udiskie'
	 'ufw'
	 'gufw'
	 'ufw-extras'
	 'vlc'
	 'youtube-dl'
	 'yay'
	 'xdotool'
	 'xf86-video-ati'
	 'xf86-video-nouveau'
	 'xf86-video-intel'
	 'xf86-video-vesa'
	 'xf86-input-synaptics'
	 'xorg'
 	 'xorg-server'
	 'xorg-xinit'
	 'xorg-fonts-100dpi'
	 'xorg-fonts-75dpi'
	 'xorg-fonts-misc'
)
